name: Seguridad - Análisis con Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Bandit
        run: pip install bandit

      - name: Ejecutar análisis de seguridad
        run: bandit -r . -f txt -lll
